-- MySQL Script generated by MySQL Workbench
-- Wed Mar  9 13:24:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema assistenciatecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assistenciatecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assistenciatecnica` DEFAULT CHARACTER SET utf8 ;
USE `assistenciatecnica` ;

-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Endereço` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Endereço` (
  `ID_Endereço` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Número` VARCHAR(10) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Endereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Contato` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Contato` (
  `ID_Contato` INT NOT NULL AUTO_INCREMENT,
  `Telefone` VARCHAR(45) NOT NULL,
  `Telefone2` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Cliente` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nome_Cliente` VARCHAR(127) NOT NULL,
  `RG_Cliente` VARCHAR(45) NULL,
  `CPF_Cliente` VARCHAR(45) NULL,
  `ID_Endereco` INT NOT NULL,
  `ID_Contato` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`, `ID_Endereco`, `ID_Contato`),
  INDEX `fk_Cliente_Endereço1_idx` (`ID_Endereco` ASC) VISIBLE,
  INDEX `fk_Cliente_Contato1_idx` (`ID_Contato` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereço1`
    FOREIGN KEY (`ID_Endereco`)
    REFERENCES `assistenciatecnica`.`Endereço` (`ID_Endereço`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Contato1`
    FOREIGN KEY (`ID_Contato`)
    REFERENCES `assistenciatecnica`.`Contato` (`ID_Contato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Funcionario` (
  `ID_Funcionario` INT NOT NULL AUTO_INCREMENT,
  `Nome_Funcionario` VARCHAR(127) NOT NULL,
  `Função` VARCHAR(45) NOT NULL,
  `RG_Funcionario` VARCHAR(45) NULL,
  `CPF_Funcionario` VARCHAR(45) NULL,
  `ID_Contato` INT NOT NULL,
  `ID_Endereco` INT NOT NULL,
  PRIMARY KEY (`ID_Funcionario`, `ID_Contato`, `ID_Endereco`),
  INDEX `fk_Cliente_Contato1_idx` (`ID_Contato` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereço1_idx` (`ID_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Contato10`
    FOREIGN KEY (`ID_Contato`)
    REFERENCES `assistenciatecnica`.`Contato` (`ID_Contato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Endereço10`
    FOREIGN KEY (`ID_Endereco`)
    REFERENCES `assistenciatecnica`.`Endereço` (`ID_Endereço`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`LoginUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`LoginUsuario` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`LoginUsuario` (
  `ID_Login` INT NOT NULL AUTO_INCREMENT,
  `ID_Funcionario_Login` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL COMMENT 'Tipo de usuário, administrador,vendedor, gerente',
  PRIMARY KEY (`ID_Login`, `ID_Funcionario_Login`),
  INDEX `fk_LoginUsuario_Funcionario1_idx` (`ID_Funcionario_Login` ASC) VISIBLE,
  CONSTRAINT `fk_LoginUsuario_Funcionario1`
    FOREIGN KEY (`ID_Funcionario_Login`)
    REFERENCES `assistenciatecnica`.`Funcionario` (`ID_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Produto` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Produto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Produto` VARCHAR(45) NOT NULL,
  `Preco_Produto` DECIMAL(10,2) NOT NULL,
  `Estoque` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Servico` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Servico` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Servico` VARCHAR(45) NOT NULL,
  `Preco_Servico` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Nota_Servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Nota_Servico` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Nota_Servico` (
  `ID_Nota_Servico` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `ID_Cliente` INT NOT NULL,
  `ID_Funcionario` INT NOT NULL,
  `Valor_Nota` DECIMAL(10,2) NOT NULL,
  `Observacoes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID_Nota_Servico`),
  INDEX `fk_Ordem_Servico_Cliente1_idx` (`ID_Cliente` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_Funcionario1_idx` (`ID_Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_Cliente1`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `assistenciatecnica`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ordem_Servico_Funcionario1`
    FOREIGN KEY (`ID_Funcionario`)
    REFERENCES `assistenciatecnica`.`Funcionario` (`ID_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Servicos_Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Servicos_Nota` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Servicos_Nota` (
  `ID_Nota_Servico` INT NOT NULL,
  `ID_Servico` INT NOT NULL,
  PRIMARY KEY (`ID_Nota_Servico`, `ID_Servico`),
  INDEX `fk_Ordem_Servico_has_Servico_Servico1_idx` (`ID_Servico` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_has_Servico_Ordem_Servico1_idx` (`ID_Nota_Servico` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_has_Servico_Ordem_Servico1`
    FOREIGN KEY (`ID_Nota_Servico`)
    REFERENCES `assistenciatecnica`.`Nota_Servico` (`ID_Nota_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_has_Servico_Servico1`
    FOREIGN KEY (`ID_Servico`)
    REFERENCES `assistenciatecnica`.`Servico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assistenciatecnica`.`Produtos_Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `assistenciatecnica`.`Produtos_Nota` ;

CREATE TABLE IF NOT EXISTS `assistenciatecnica`.`Produtos_Nota` (
  `ID_Nota_Produto` INT NOT NULL,
  `ID_Produto` INT NOT NULL,
  PRIMARY KEY (`ID_Nota_Produto`, `ID_Produto`),
  INDEX `fk_Ordem_Servico_has_Produto_Produto1_idx` (`ID_Produto` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_has_Produto_Ordem_Servico1_idx` (`ID_Nota_Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_has_Produto_Ordem_Servico1`
    FOREIGN KEY (`ID_Nota_Produto`)
    REFERENCES `assistenciatecnica`.`Nota_Servico` (`ID_Nota_Servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem_Servico_has_Produto_Produto1`
    FOREIGN KEY (`ID_Produto`)
    REFERENCES `assistenciatecnica`.`Produto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
