-- MySQL Script generated by MySQL Workbench
-- Thu Jan 27 15:36:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AssistenciaTecnica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AssistenciaTecnica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AssistenciaTecnica` DEFAULT CHARACTER SET utf8 ;
USE `AssistenciaTecnica` ;

-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Contato` (
  `ID_Contato` INT NOT NULL AUTO_INCREMENT,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Contato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Endereço` (
  `ID_Endereço` INT NOT NULL AUTO_INCREMENT,
  `Logradouro` VARCHAR(45) NOT NULL,
  `Número` VARCHAR(10) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Endereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Cliente` (
  `ID_Cliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(127) NOT NULL,
  `R.G` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `ID_Contato_Cliente` INT NOT NULL,
  `ID_Endereco_Cliente` INT NOT NULL,
  PRIMARY KEY (`ID_Cliente`, `ID_Contato_Cliente`, `ID_Endereco_Cliente`),
  INDEX `fk_Cliente_Contato1_idx` (`ID_Contato_Cliente` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereço1_idx` (`ID_Endereco_Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Contato1`
    FOREIGN KEY (`ID_Contato_Cliente`)
    REFERENCES `AssistenciaTecnica`.`Contato` (`ID_Contato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Endereço1`
    FOREIGN KEY (`ID_Endereco_Cliente`)
    REFERENCES `AssistenciaTecnica`.`Endereço` (`ID_Endereço`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Funcionario` (
  `ID_Funcionario` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(127) NOT NULL,
  `Função` VARCHAR(45) NOT NULL,
  `R.G` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `ID_Contato_Funcionario` INT NOT NULL,
  `ID_Endereco_Funcionario` INT NOT NULL,
  PRIMARY KEY (`ID_Funcionario`, `ID_Contato_Funcionario`, `ID_Endereco_Funcionario`),
  INDEX `fk_Cliente_Contato1_idx` (`ID_Contato_Funcionario` ASC) VISIBLE,
  INDEX `fk_Cliente_Endereço1_idx` (`ID_Endereco_Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Contato10`
    FOREIGN KEY (`ID_Contato_Funcionario`)
    REFERENCES `AssistenciaTecnica`.`Contato` (`ID_Contato`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cliente_Endereço10`
    FOREIGN KEY (`ID_Endereco_Funcionario`)
    REFERENCES `AssistenciaTecnica`.`Endereço` (`ID_Endereço`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`LoginUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`LoginUsuario` (
  `ID_Login` INT NOT NULL AUTO_INCREMENT,
  `ID_Funcionario_Login` INT NOT NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL COMMENT 'Tipo de usuário, administrador,vendedor, gerente',
  PRIMARY KEY (`ID_Login`, `ID_Funcionario_Login`),
  INDEX `fk_LoginUsuario_Funcionario1_idx` (`ID_Funcionario_Login` ASC) VISIBLE,
  CONSTRAINT `fk_LoginUsuario_Funcionario1`
    FOREIGN KEY (`ID_Funcionario_Login`)
    REFERENCES `AssistenciaTecnica`.`Funcionario` (`ID_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Produto` (
  `ID_Produto` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Preco` DECIMAL NOT NULL,
  PRIMARY KEY (`ID_Produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Servico` (
  `ID_Servico` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Preco` DECIMAL NOT NULL,
  PRIMARY KEY (`ID_Servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AssistenciaTecnica`.`Ordem_Servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AssistenciaTecnica`.`Ordem_Servico` (
  `ID_Ordem_Servico` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NOT NULL,
  `ID_Produto` INT NOT NULL,
  `ID_Servico` INT NOT NULL,
  `ID_Cliente` INT NOT NULL,
  `ID_Funcionario` INT NOT NULL,
  `Observacoes` MEDIUMTEXT NULL,
  PRIMARY KEY (`ID_Ordem_Servico`),
  INDEX `fk_Ordem_Servico_Produto1_idx` (`ID_Produto` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_Servico1_idx` (`ID_Servico` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_Cliente1_idx` (`ID_Cliente` ASC) VISIBLE,
  INDEX `fk_Ordem_Servico_Funcionario1_idx` (`ID_Funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem_Servico_Produto1`
    FOREIGN KEY (`ID_Produto`)
    REFERENCES `AssistenciaTecnica`.`Produto` (`ID_Produto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ordem_Servico_Servico1`
    FOREIGN KEY (`ID_Servico`)
    REFERENCES `AssistenciaTecnica`.`Servico` (`ID_Servico`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ordem_Servico_Cliente1`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `AssistenciaTecnica`.`Cliente` (`ID_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ordem_Servico_Funcionario1`
    FOREIGN KEY (`ID_Funcionario`)
    REFERENCES `AssistenciaTecnica`.`Funcionario` (`ID_Funcionario`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
